In [693]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np
from collections import Counter
from math import sqrt
from numpy import ndarray

# Importing Datasets

## Iris

In [694]:
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris['data'], iris['target'], random_state=2022) # 75% training and 25% test 

In [695]:
print(X_train)
print(y_train)

[[5.1 3.8 1.9 0.4]
 [5.2 2.7 3.9 1.4]
 [6.5 3.  5.2 2. ]
 [5.6 3.  4.5 1.5]
 [4.9 2.4 3.3 1. ]
 [7.3 2.9 6.3 1.8]
 [6.9 3.1 5.4 2.1]
 [6.3 3.4 5.6 2.4]
 [7.1 3.  5.9 2.1]
 [6.9 3.2 5.7 2.3]
 [4.6 3.1 1.5 0.2]
 [5.9 3.  5.1 1.8]
 [6.  2.9 4.5 1.5]
 [6.2 3.4 5.4 2.3]
 [6.7 3.1 5.6 2.4]
 [6.4 2.8 5.6 2.2]
 [4.6 3.6 1.  0.2]
 [7.  3.2 4.7 1.4]
 [5.4 3.  4.5 1.5]
 [5.1 3.8 1.5 0.3]
 [6.1 2.8 4.  1.3]
 [5.  3.2 1.2 0.2]
 [5.  3.5 1.3 0.3]
 [5.7 2.8 4.1 1.3]
 [6.5 2.8 4.6 1.5]
 [5.  2.  3.5 1. ]
 [7.7 3.8 6.7 2.2]
 [6.7 3.  5.2 2.3]
 [6.7 3.1 4.7 1.5]
 [6.1 2.8 4.7 1.2]
 [7.2 3.6 6.1 2.5]
 [5.  3.  1.6 0.2]
 [5.4 3.7 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.2 4.1 1.5 0.1]
 [6.  2.2 4.  1. ]
 [6.5 3.2 5.1 2. ]
 [6.7 3.1 4.4 1.4]
 [5.  3.4 1.5 0.2]
 [5.  3.4 1.6 0.4]
 [5.4 3.4 1.5 0.4]
 [6.1 3.  4.9 1.8]
 [5.9 3.2 4.8 1.8]
 [4.9 3.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [5.7 2.8 4.5 1.3]
 [5.  3.3 1.4 0.2]
 [4.6 3.2 1.4 0.2]
 [6.5 3.  5.8 2.2]
 [4.7 3.2 1.6 0.2]
 [6.9 3.1 5.1 2.3]
 [6.4 3.2 4.5 1.5]
 [6.3 2.7 4.

## Ionosphere

In [696]:
X = np.genfromtxt("ionosphere.txt", delimiter=',', dtype='int') 
X = X[:, :-1] 
y = np.genfromtxt("ionosphere.txt", delimiter=',', dtype='int')
y = y[:, -1]

In [697]:
print(X)
print(y)

[[ 1  0 -1 ... -1 -1 -1]
 [ 1  0  1 ... -1 -1 -1]
 [ 1  0  1 ... -1 -1 -1]
 ...
 [ 1  0 -1 ... -1 -1 -1]
 [ 1  0 -1 ... -1 -1 -1]
 [ 1  0 -1 ... -1 -1 -1]]
[ 1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1
  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1
  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1
  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1
  1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  

# Sorting Algorithms

In [698]:
class Sorting:
	@staticmethod
	def arg_sort(seq: list) -> list:
		# return np.argsort(seq)
		return sorted(range(len(seq)), key=seq.__getitem__)

	@staticmethod
	def merge_sort(seq: list) -> list:
		if len(seq) <= 1:
			return seq
		mid = len(seq) // 2
		left = Sorting.merge_sort(seq[:mid])
		right = Sorting.merge_sort(seq[mid:])
		return Sorting.merge(left, right)

	@staticmethod
	def merge(left: list, right: list) -> list:
		result = []
		while len(left) > 0 and len(right) > 0:
			if left[0] <= right[0]:
				result.append(left.pop(0))
			else:
				result.append(right.pop(0))
		if len(left) > 0:
			result.extend(left)
		if len(right) > 0:
			result.extend(right)
		return result

	@staticmethod
	def quick_sort(seq: list) -> list:
		if len(seq) <= 1:
			return seq
		pivot = seq.pop()
		left = []
		right = []
		for item in seq:
			if item <= pivot:
				left.append(item)
			else:
				right.append(item)
		return Sorting.quick_sort(left) + [pivot] + Sorting.quick_sort(right)

	@staticmethod
	def bubble_sort(seq: list) -> list:
		for i in range(len(seq)):
			for j in range(i + 1, len(seq)):
				if seq[i] > seq[j]:
					seq[i], seq[j] = seq[j], seq[i]
		return seq

	@staticmethod
	def selection_sort(seq: list) -> list:
		for i in range(len(seq)):
			min_index = i
			for j in range(i + 1, len(seq)):
				if seq[j] < seq[min_index]:
					min_index = j
			seq[i], seq[min_index] = seq[min_index], seq[i]
		return seq

	@staticmethod
	def insertion_sort(seq: list) -> list:
		for i in range(1, len(seq)):
			j = i
			while j > 0 and seq[j] < seq[j - 1]:
				seq[j], seq[j - 1] = seq[j - 1], seq[j]
				j -= 1
		return seq

	@staticmethod
	def heap_sort(seq: list) -> list:
		heap = []
		for item in seq:
			heap.append(item)
			Sorting.sift_up(heap, len(heap) - 1)
		result = []
		while len(heap) > 0:
			result.append(heap[0])
			heap[0] = heap[-1]
			heap.pop()
			Sorting.sift_down(heap, 0)
		return result	

# Nearest Neighbour Algorithms

## K-Nearest Neighbour

In [699]:
class Knn:
	def __init__(self, k: int):
		self.k: int = k
		self.X_train: list = None
		self.y_train: list = None

	def fit(self, X_train: list, y_train: list) -> None:
		self.X_train = X_train
		self.y_train = y_train

	def predict(self, X_test: list) -> list[int]:
		predictions: list = []
		for index, element in enumerate(X_test):
			predictions.append(self._predict(element))
		return predictions
	
	def _predict(self, x_test: list) -> int:
		distances: list = self.distance(self.X_train, x_test)
		k_indices: list = self.sort(distances, "arg_sort")[:self.k]
		k_nearest_labels: list = [self.y_train[i] for i in k_indices]
		most_common: list[tuple] = Counter(k_nearest_labels).most_common(1)
		return most_common[0][0]

	def score(self, X_test: list, y_test: list) -> float:
		predictions: list = self.predict(X_test)
		return self.accuracy_score(y_test, predictions)

	def accuracy_score(self, y_test, y_pred) -> float:
		accuracy: float = sum(y_test == y_pred) / len(y_test)
		return accuracy

	def distance(self, x1: list, x2: list) -> list[float]:
		return [((sum((x1 - x2)**2)) ** 0.5) for (x1) in (self.X_train)]

	def sort(self, distances, sorting_type = "arg_sort"):
		if sorting_type == "arg_sort":
			return Sorting.arg_sort(distances)
		elif sorting_type == "merge_sort":
			return Sorting.merge_sort(distances)
		elif sorting_type == "quick_sort":
			return Sorting.quick_sort(distances)


## Iris Dataset

In [700]:
knn: Knn = Knn(k=3)
knn.fit(X_train, y_train)
predictions: list = knn.predict(X_test)
compare = pd.DataFrame({'True Labels': y_test, 'Predicted Labels': predictions})
accuracy: float = knn.score(X_test, y_test)
error_rate: float = 1 - accuracy

In [701]:
print("Predictions: ", predictions)
print("Accuracy: ", accuracy)
print("Error Rate: ", 1 - accuracy)
print("Comparison: \n", compare)

Predictions:  [2, 2, 0, 2, 0, 0, 1, 1, 0, 1, 1, 2, 1, 2, 2, 0, 1, 2, 2, 1, 0, 0, 2, 0, 2, 1, 2, 0, 1, 2, 0, 1, 1, 0, 1, 0, 0, 1]
Accuracy:  0.9736842105263158
Error Rate:  0.02631578947368418
Comparison: 
     True Labels  Predicted Labels
0             2                 2
1             2                 2
2             0                 0
3             2                 2
4             0                 0
5             0                 0
6             1                 1
7             1                 1
8             0                 0
9             1                 1
10            1                 1
11            2                 2
12            1                 1
13            2                 2
14            2                 2
15            0                 0
16            1                 1
17            2                 2
18            2                 2
19            1                 1
20            0                 0
21            0                 0
22          

## Ionosphere Dataset

In [702]:
knn.fit(X, y)
predictions: list = knn.predict(X)
compare = pd.DataFrame({'True Labels': y, 'Predicted Labels': predictions})
accuracy: float = knn.score(X, y)
error_rate: float = 1 - accuracy

In [703]:
print("Predictions: ", predictions)
print("Accuracy: ", accuracy)
print("Error Rate: ", 1 - accuracy)
print("Comparison: \n", compare)

Predictions:  [1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -1, 1, -1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, -1, 1, -1, 1, -1, -1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 1, -1, 1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, -1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

## 1 Nearest Neighbour

In [704]:
class OneNN:
	def __init__(self):
		self.k: int = 1
		self.X_train: list = None
		self.y_train: list = None

	def fit(self, X_train: list, y_train: list) -> None:
		self.X_train = X_train
		self.y_train = y_train

	def predict(self, X_test: list) -> list[int]:
		predictions: list = []
		for index, element in enumerate(X_test):
			predictions.append(self._predict(element))
		return predictions
	
	def _predict(self, x_test: list) -> int:
		distances: list = self.distance(self.X_train, x_test)
		k_indices: list = self.sort(distances, "arg_sort")[:self.k]
		k_nearest_labels: list = [self.y_train[i] for i in k_indices]
		most_common: list[tuple] = Counter(k_nearest_labels).most_common(1)
		return most_common[0][0]

	def score(self, X_test: list, y_test: list) -> float:
		predictions: list = self.predict(X_test)
		return self.accuracy_score(y_test, predictions)

	def accuracy_score(self, y_test, y_pred) -> float:
		accuracy: float = sum(y_test == y_pred) / len(y_test)
		return accuracy

	def distance(self, x1: list, x2: list) -> list[float]:
		return [((sum((x1 - x2)**2)) ** 0.5) for (x1) in (self.X_train)]

	def sort(self, distances, sorting_type = "arg_sort"):
		if sorting_type == "arg_sort":
			return Sorting.arg_sort(distances)
		elif sorting_type == "merge_sort":
			return Sorting.merge_sort(distances)
		elif sorting_type == "quick_sort":
			return Sorting.quick_sort(distances)

## Iris Dataset

In [705]:
onenn: OneNN = OneNN()
onenn.fit(X_train, y_train)
predictions: list = onenn.predict(X_test)
compare = pd.DataFrame({'True Labels': y_test, 'Predicted Labels': predictions})
accuracy: float = onenn.score(X_test, y_test)
error_rate: float = 1 - accuracy

In [706]:
print("Predictions: ", predictions)
print("Accuracy: ", accuracy)
print("Error Rate: ", 1 - accuracy)
print("Comparison: \n", compare)

Predictions:  [2, 2, 0, 2, 0, 0, 1, 1, 0, 1, 1, 2, 1, 2, 2, 0, 1, 2, 2, 1, 0, 0, 2, 0, 2, 1, 2, 0, 1, 2, 0, 1, 1, 0, 1, 0, 0, 1]
Accuracy:  0.9736842105263158
Error Rate:  0.02631578947368418
Comparison: 
     True Labels  Predicted Labels
0             2                 2
1             2                 2
2             0                 0
3             2                 2
4             0                 0
5             0                 0
6             1                 1
7             1                 1
8             0                 0
9             1                 1
10            1                 1
11            2                 2
12            1                 1
13            2                 2
14            2                 2
15            0                 0
16            1                 1
17            2                 2
18            2                 2
19            1                 1
20            0                 0
21            0                 0
22          

## Ionosphere Dataset

In [707]:
onenn.fit(X, y)
predictions: list = onenn.predict(X)
compare = pd.DataFrame({'True Labels': y, 'Predicted Labels': predictions})
accuracy: float = onenn.score(X, y)
error_rate: float = 1 - accuracy

In [708]:
print("Predictions: ", predictions)
print("Accuracy: ", accuracy)
print("Error Rate: ", 1 - accuracy)
print("Comparison: \n", compare)

Predictions:  [1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, -1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, -1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 1, 1, -1, 1, -1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, -1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

## 3 Nearest Neighbour

In [714]:
class ThreeNN:
	def __init__(self):
		self.k: int = 3
		self.X_train: list = None
		self.y_train: list = None

	def fit(self, X_train: list, y_train: list) -> None:
		self.X_train = X_train
		self.y_train = y_train

	def predict(self, X_test: list) -> list[int]:
		predictions: list = []
		for index, element in enumerate(X_test):
			predictions.append(self._predict(element))
		return predictions
	
	def _predict(self, x_test: list) -> int:
		distances: list = self.distance(self.X_train, x_test)
		k_indices: list = self.sort(distances, "arg_sort")[:self.k]
		k_nearest_labels: list = [self.y_train[i] for i in k_indices]
		most_common: list[tuple] = Counter(k_nearest_labels).most_common(1)
		return most_common[0][0]

	def score(self, X_test: list, y_test: list) -> float:
		predictions: list = self.predict(X_test)
		return self.accuracy_score(y_test, predictions)

	def accuracy_score(self, y_test, y_pred) -> float:
		accuracy: float = sum(y_test == y_pred) / len(y_test)
		return accuracy

	def distance(self, x1: list, x2: list) -> list[float]:
		return [((sum((x1 - x2)**2)) ** 0.5) for (x1) in (self.X_train)]

	def sort(self, distances, sorting_type = "arg_sort"):
		if sorting_type == "arg_sort":
			return Sorting.arg_sort(distances)
		elif sorting_type == "merge_sort":
			return Sorting.merge_sort(distances)
		elif sorting_type == "quick_sort":
			return Sorting.quick_sort(distances)

## Iris Dataset

In [715]:
threenn: ThreeNN = ThreeNN()
threenn.fit(X_train, y_train)
predictions: list = threenn.predict(X_test)
compare = pd.DataFrame({'True Labels': y_test, 'Predicted Labels': predictions})
accuracy: float = threenn.score(X_test, y_test)
error_rate: float = 1 - accuracy

In [716]:
print("Predictions: ", predictions)
print("Accuracy: ", accuracy)
print("Error Rate: ", 1 - accuracy)
print("Comparison: \n", compare)

Predictions:  [2, 2, 0, 2, 0, 0, 1, 1, 0, 1, 1, 2, 1, 2, 2, 0, 1, 2, 2, 1, 0, 0, 2, 0, 2, 1, 2, 0, 1, 2, 0, 1, 1, 0, 1, 0, 0, 1]
Accuracy:  0.9736842105263158
Error Rate:  0.02631578947368418
Comparison: 
     True Labels  Predicted Labels
0             2                 2
1             2                 2
2             0                 0
3             2                 2
4             0                 0
5             0                 0
6             1                 1
7             1                 1
8             0                 0
9             1                 1
10            1                 1
11            2                 2
12            1                 1
13            2                 2
14            2                 2
15            0                 0
16            1                 1
17            2                 2
18            2                 2
19            1                 1
20            0                 0
21            0                 0
22          

## Ionosphere Dataset

In [717]:
threenn.fit(X, y)
predictions: list = threenn.predict(X)
compare = pd.DataFrame({'True Labels': y, 'Predicted Labels': predictions})
accuracy: float = threenn.score(X, y)
error_rate: float = 1 - accuracy

In [718]:
print("Predictions: ", predictions)
print("Accuracy: ", accuracy)
print("Error Rate: ", 1 - accuracy)
print("Comparison: \n", compare)

Predictions:  [1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -1, 1, -1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, -1, 1, -1, 1, -1, -1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 1, -1, 1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, -1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

# Conformal Predictor

In [713]:
# create conformal predictor 
import math
def calculate_distance(X_train, y_train):
    train_length = X_train.shape[0]
    same_class_dist, other_class_dist = [[math.inf for i in range(train_length)] for j in range(2)]

    for i in range(train_length-1):
        for j in range(i+1, train_length):
            dist = np.sqrt(np.sum((X_train[i] - X_train[j])**2))
            if y_train[i] == y_train[j]:
                if dist < same_class_dist[i]:
                    same_class_dist[i] = dist
                if dist < same_class_dist[j]:
                    same_class_dist[j] = dist
            else:
                if dist < other_class_dist[i]:
                    other_class_dist[i] = dist
                if dist < other_class_dist[j]:
                    other_class_dist[j] = dist
    return same_class_dist, other_class_dist

def calculate_p_value(same_class_dist, other_class_dist):
    p_values = []
    for i in range(len(same_class_dist)):
        p_values.append(same_class_dist[i] / (same_class_dist[i] + other_class_dist[i]))
    return p_values

def calculate_alpha(p_values, alpha):
    p_values.sort()
    return p_values[int(len(p_values) * alpha)]

def calculate_conformal_prediction(X_train, y_train, X_test, alpha):
    same_class_dist, other_class_dist = calculate_distance(X_train, y_train)
    p_values = calculate_p_value(same_class_dist, other_class_dist)
    alpha = calculate_alpha(p_values, alpha)
    predictions = []
    for i in range(len(X_test)):
        dist = np.sqrt(np.sum((X_train - X_test[i])**2))
        p_values = dist / (dist + other_class_dist)
        predictions.append(p_values > alpha)
    return predictions

# calculate p-values
same_class_dist, other_class_dist = calculate_distance(X_train, y_train)
p_values = calculate_p_value(same_class_dist, other_class_dist)
