In [121]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np
from collections import Counter

# Importing Datasets

## Iris

In [122]:
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris['data'], iris['target'], random_state=2022) # 75% training and 25% test 

In [123]:
print(X_train)
print(y_train)

[[5.1 3.8 1.9 0.4]
 [5.2 2.7 3.9 1.4]
 [6.5 3.  5.2 2. ]
 [5.6 3.  4.5 1.5]
 [4.9 2.4 3.3 1. ]
 [7.3 2.9 6.3 1.8]
 [6.9 3.1 5.4 2.1]
 [6.3 3.4 5.6 2.4]
 [7.1 3.  5.9 2.1]
 [6.9 3.2 5.7 2.3]
 [4.6 3.1 1.5 0.2]
 [5.9 3.  5.1 1.8]
 [6.  2.9 4.5 1.5]
 [6.2 3.4 5.4 2.3]
 [6.7 3.1 5.6 2.4]
 [6.4 2.8 5.6 2.2]
 [4.6 3.6 1.  0.2]
 [7.  3.2 4.7 1.4]
 [5.4 3.  4.5 1.5]
 [5.1 3.8 1.5 0.3]
 [6.1 2.8 4.  1.3]
 [5.  3.2 1.2 0.2]
 [5.  3.5 1.3 0.3]
 [5.7 2.8 4.1 1.3]
 [6.5 2.8 4.6 1.5]
 [5.  2.  3.5 1. ]
 [7.7 3.8 6.7 2.2]
 [6.7 3.  5.2 2.3]
 [6.7 3.1 4.7 1.5]
 [6.1 2.8 4.7 1.2]
 [7.2 3.6 6.1 2.5]
 [5.  3.  1.6 0.2]
 [5.4 3.7 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.2 4.1 1.5 0.1]
 [6.  2.2 4.  1. ]
 [6.5 3.2 5.1 2. ]
 [6.7 3.1 4.4 1.4]
 [5.  3.4 1.5 0.2]
 [5.  3.4 1.6 0.4]
 [5.4 3.4 1.5 0.4]
 [6.1 3.  4.9 1.8]
 [5.9 3.2 4.8 1.8]
 [4.9 3.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [5.7 2.8 4.5 1.3]
 [5.  3.3 1.4 0.2]
 [4.6 3.2 1.4 0.2]
 [6.5 3.  5.8 2.2]
 [4.7 3.2 1.6 0.2]
 [6.9 3.1 5.1 2.3]
 [6.4 3.2 4.5 1.5]
 [6.3 2.7 4.

## Ionosphere

In [124]:
X = np.genfromtxt("ionosphere.txt", delimiter=',', dtype='int') 
X = X[:, :-1] 
y = np.genfromtxt("ionosphere.txt", delimiter=',', dtype='int')
y = y[:, -1]

In [125]:
print(X)
print(y)

[[ 1  0 -1 ... -1 -1 -1]
 [ 1  0  1 ... -1 -1 -1]
 [ 1  0  1 ... -1 -1 -1]
 ...
 [ 1  0 -1 ... -1 -1 -1]
 [ 1  0 -1 ... -1 -1 -1]
 [ 1  0 -1 ... -1 -1 -1]]
[ 1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1
  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1
  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1
  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1
  1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  

# Nearest Neighbour Algorithms

## K-Nearest Neighbour

In [126]:
class Knn:
	def __init__(self, k):
		self.k = k
		self.X_train = None
		self.y_train = None

	def fit(self, X_train, y_train):
		self.X_train = X_train
		self.y_train = y_train

	def predict(self, X_test):
		predictions = []
		for i in range(len(X_test)):
			predictions.append(self._predict(X_test[i]))
		return predictions
	
	def _predict(self, x_test):
		# distances = [np.sqrt(np.sum((x_train - x_test)**2)) for x_train in self.X_train]
		distances = self.distance(self.X_train, x_test)
		k_indices = np.argsort(distances)[:self.k]
		k_nearest_labels = [self.y_train[i] for i in k_indices]
		most_common = Counter(k_nearest_labels).most_common(1)
		return most_common[0][0]

	def score(self, X_test, y_test):
		predictions = self.predict(X_test)
		return self.accuracy_score(y_test, predictions)

	def accuracy_score(self, y_test, y_pred):
		accuracy = np.sum(y_test == y_pred) / len(y_test)
		return accuracy

	def distance(self, x1, x2):
		return [np.sqrt(np.sum((x1 - x2)**2)) for x1 in self.X_train]

## Iris Dataset

In [127]:
knn = Knn(k=3)
knn.fit(X_train, y_train)
predictions = knn.predict(X_test)
compare = pd.DataFrame({'True Labels': y_test, 'Predicted Labels': predictions})
accuracy = knn.score(X_test, y_test)
error_rate = 1 - accuracy

In [128]:
print("Predictions: ", predictions)
print("Accuracy: ", knn.score(X_test, y_test))
print("Error Rate: ", 1 - knn.score(X_test, y_test))
print("Comparison: \n", compare)


Predictions:  [2, 2, 0, 2, 0, 0, 1, 1, 0, 1, 1, 2, 1, 2, 2, 0, 1, 2, 2, 1, 0, 0, 2, 0, 2, 1, 2, 0, 1, 2, 0, 1, 1, 0, 1, 0, 0, 1]
Accuracy:  0.9736842105263158
Error Rate:  0.02631578947368418
Comparison: 
     True Labels  Predicted Labels
0             2                 2
1             2                 2
2             0                 0
3             2                 2
4             0                 0
5             0                 0
6             1                 1
7             1                 1
8             0                 0
9             1                 1
10            1                 1
11            2                 2
12            1                 1
13            2                 2
14            2                 2
15            0                 0
16            1                 1
17            2                 2
18            2                 2
19            1                 1
20            0                 0
21            0                 0
22          

## Ionosphere Dataset

In [129]:
knn.fit(X, y)
predictions = knn.predict(X)
print(knn.score(X, y))

0.9116809116809117


## 1 Nearest Neighbour

In [130]:
class OneNN:
	def __init__(self):
		self.X_train = None
		self.y_train = None

	def fit(self, X_train, y_train):
		self.X_train = X_train
		self.y_train = y_train

	def predict(self, X_test):
		predictions = []
		for i in range(len(X_test)):
			predictions.append(self._predict(X_test[i]))
		return predictions
	
	def _predict(self, x_test):
		distances = [np.sqrt(np.sum((x_train - x_test)**2)) for x_train in self.X_train]
		k_indices = np.argsort(distances)[:1]
		k_nearest_labels = [self.y_train[i] for i in k_indices]
		most_common = Counter(k_nearest_labels).most_common(1)
		return most_common[0][0]

	def score(self, X_test, y_test):
		predictions = self.predict(X_test)
		return self.accuracy_score(y_test, predictions)

	def accuracy_score(self, y_test, y_pred):
		accuracy = np.sum(y_test == y_pred) / len(y_test)
		return accuracy

	def distance(self, x1, x2):
		return (np.sum((x1 - x2)**2) ** 0.5)

	def get_predictions(self, X_test):
		predictions = []
		for i in range(len(X_test)):
			predictions.append(self._predict(X_test[i]))
		return predictions

## 3 Nearest Neighbour

In [131]:
class ThreeNN:
	def __init__(self):
		self.X_train = None
		self.y_train = None

	def fit(self, X_train, y_train):
		self.X_train = X_train
		self.y_train = y_train

	def predict(self, X_test):
		predictions = []
		for i in range(len(X_test)):
			predictions.append(self._predict(X_test[i]))
		return predictions
	
	def _predict(self, x_test):
		distances = [np.sqrt(np.sum((x_train - x_test)**2)) for x_train in self.X_train]
		k_indices = np.argsort(distances)[:3]
		k_nearest_labels = [self.y_train[i] for i in k_indices]
		most_common = Counter(k_nearest_labels).most_common(1)
		return most_common[0][0]

	def score(self, X_test, y_test):
		predictions = self.predict(X_test)
		return self.accuracy_score(y_test, predictions)

	def accuracy_score(self, y_test, y_pred):
		accuracy = np.sum(y_test == y_pred) / len(y_test)
		return accuracy

In [132]:
knn = OneNN()
knn.fit(X_train, y_train)
predictions = knn.predict(X_test)
print("Accuracy: ", knn.score(X_test, y_test))
print("Error Rate: ", 1 - knn.score(X_test, y_test))

knn = ThreeNN()
knn.fit(X_train, y_train)
predictions = knn.predict(X_test)
print("Accuracy: ", knn.score(X_test, y_test))
print("Error Rate: ", 1 - knn.score(X_test, y_test))

Accuracy:  0.9736842105263158
Error Rate:  0.02631578947368418
Accuracy:  0.9736842105263158
Error Rate:  0.02631578947368418


In [133]:
# ionosphere
knn = OneNN()
knn.fit(X, y)
predictions = knn.predict(X) 
print(knn.score(X, y))

0.9715099715099715


# Conformal Predictor

In [134]:
# create conformal predictor 
import math
def calculate_distance(X_train, y_train):
    train_length = X_train.shape[0]
    same_class_dist, other_class_dist = [[math.inf for i in range(train_length)] for j in range(2)]

    for i in range(train_length-1):
        for j in range(i+1, train_length):
            dist = np.sqrt(np.sum((X_train[i] - X_train[j])**2))
            if y_train[i] == y_train[j]:
                if dist < same_class_dist[i]:
                    same_class_dist[i] = dist
                if dist < same_class_dist[j]:
                    same_class_dist[j] = dist
            else:
                if dist < other_class_dist[i]:
                    other_class_dist[i] = dist
                if dist < other_class_dist[j]:
                    other_class_dist[j] = dist
    return same_class_dist, other_class_dist

def calculate_p_value(same_class_dist, other_class_dist):
    p_values = []
    for i in range(len(same_class_dist)):
        p_values.append(same_class_dist[i] / (same_class_dist[i] + other_class_dist[i]))
    return p_values

def calculate_alpha(p_values, alpha):
    p_values.sort()
    return p_values[int(len(p_values) * alpha)]

def calculate_conformal_prediction(X_train, y_train, X_test, alpha):
    same_class_dist, other_class_dist = calculate_distance(X_train, y_train)
    p_values = calculate_p_value(same_class_dist, other_class_dist)
    alpha = calculate_alpha(p_values, alpha)
    predictions = []
    for i in range(len(X_test)):
        dist = np.sqrt(np.sum((X_train - X_test[i])**2))
        p_values = dist / (dist + other_class_dist)
        predictions.append(p_values > alpha)
    return predictions

# calculate p-values
same_class_dist, other_class_dist = calculate_distance(X_train, y_train)
p_values = calculate_p_value(same_class_dist, other_class_dist)
